#!/bin/bash
set -e

psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<-EOSQL
  CREATE ROLE ${APP_DB_USER} WITH LOGIN PASSWORD '${APP_DB_PASSWORD}';

  CREATE SCHEMA IF NOT EXISTS nommie;

  GRANT USAGE ON SCHEMA nommie TO ${APP_DB_USER};
  GRANT CREATE ON SCHEMA nommie TO ${APP_DB_USER};

  GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA nommie TO ${APP_DB_USER};
  GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA nommie TO ${APP_DB_USER};

  ALTER DEFAULT PRIVILEGES IN SCHEMA nommie
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${APP_DB_USER};

  ALTER DEFAULT PRIVILEGES IN SCHEMA nommie
    GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${APP_DB_USER};

  ALTER ROLE ${APP_DB_USER} SET search_path TO nommie;
EOSQL
