services:
  postgres:
    image: postgres:16
    container_name: nommie-postgres
    environment:
      POSTGRES_DB: nommie
      POSTGRES_USER: nommie_user
      POSTGRES_PASSWORD: pineconescamping
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nommie_user -d nommie"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local 
